name: 'https://thegrid.ai/stember'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.05513784
title: STORYS
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4419579482637346
  lightness: 0.5093985
  saturation: 0.5225564
  rhythmicContrast: 0.5275689
purpose: []
